
spring:
  datasource:
    url: jdbc:mysql://localhost/test?autoreconnect=true&characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: iaasadmin
    password: bmwm6cab
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: dev

foo:
  a: 11
  obj:
    b: 22
    c: xinxin
